### ISSUE TITLE
Using NextJS: Build works locally, but fails during AWS Amplify build process

### ISSUE THREAD

**Issue by 19Sean96** [sendinblue/APIv3-nodejs-library#120]
I do not submit issues often, so please let me know if I miss any information below and I'll happily provide what I can.

**Package.json Info**
```
1. sib-api-v3-sdk version: "^8.3.0"
2. next version: "latest"
```

**Amplify.yml file:**
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Error Information: **
 - Running `next build` (or `yarn run build`) on my local machine runs successfully.
 - Running the build command on our amplify site _**without**_ sib-api-v3-sdk version installed, runs successfully
 
**The problem**
When amplify begins to run the SSR build process, it fails with exit code 1 due to not being able to resolve modules within the `sib-api-v3-sdk/src` directory. 
Example:
```
Module not found: Can't resolve 'ApiClient' in '/codebuild/output/src541033312/src/WireWise-Marketing/node_modules/sib-api-v3-sdk/src'
                                  Did you mean './ApiClient'?
```

It seems all other modules within this package are also not being resolved, and I'm at a loss for words as to why this could be occuring. I will attach the build log file for further information. 

[log.txt](https://github.com/sendinblue/APIv3-nodejs-library/files/8624687/log.txt)
